# rest client extension requried 
GET http://localhost:4000/get-user

###

POST http://localhost:4000/create-user
Content-Type: application/json

{
    "email":"jsdlkhhjjefds"
}

###

POST http://localhost:4000/create-booking
Content-Type: application/json

{
    "name": "sai teja",
    "email": "teja20@gmail.com",
    "date": "Thu Sep 21 2023",
    "time":"04:00 AM"
}

###

GET http://localhost:4000/get-booking

###

DELETE http://localhost:4000/del-booking/64edc79cdf4c11c72d526696